Add a --no-empty flag to disallow empty env vars
relaxdiego/renderest pull request #1
Opened 2017-07-11 15:45 UTC by Globegitter

Just to have some stricter error checking when we know we do not want any empty env variables.

2017-07-11 22:00 UTC, relaxdiego commented
Thanks @globegitter! (Awesome nick, BTW!)

Before I can merge this, can you add a test for this in test-render? You might need to add a 3 arg to the it() function where you can pass the --no-empty flag.

2017-07-13 14:32 UTC, Globegitter commented
Done.

2017-07-14 13:12 UTC, relaxdiego requested changes

2017-07-14 13:12 UTC, relaxdiego commented on test-render
> +it "doesn' throw an error if test_variable is defined but empty and --no-empty flag is provided on last position" "test_variable=" "" "--no-empty" <<EOF
Thanks for adding the tests, @Globegitter! I was going to argue that it should work no matter where the flag is placed but thankfully I had the sense to review my POSIX and realized that you were right in doing this. :-)

Just one tiny nitpick though: Can you add the `t` to `doesn'` above?

2017-07-14 13:37 UTC, relaxdiego approved these changes

2017-07-14 13:37 UTC, merged

2017-07-14 13:38 UTC, relaxdiego commented
Thanks @Globegitter! First PR merged. W00t! This deserves a beer! 🍻

2017-07-14 13:44 UTC, Globegitter commented
Thank you - I have to say from all the simple templating solutions out there I liked yours ones the most - there is not many that kept it that simple :)